name: invoice_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  go_router: ^15.2.0
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.1
  dotted_border: ^3.0.1
  flutter_contacts: ^1.1.9+2
  signature: ^6.3.0
  # pdf
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0
  # db
  sqflite: ^2.4.2
  path: ^1.9.1
  # pro
  purchases_flutter: ^8.10.2
  purchases_ui_flutter: ^8.10.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: w800
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
